#!/usr/bin/env python3
"""Download the three webfonts and rewrite them as a local stylesheet.

A bar's shared wifi is the whole design constraint of this app, and a Google
Fonts link costs a DNS lookup, a TLS handshake and a round trip to a third party
before a single glyph is drawn -- on the connection least able to afford it. It
is also a dependency on a host the venue may block outright.

Run once; the output is committed.

    python3 tools/fetch_fonts.py
"""

from __future__ import annotations

import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FONT_DIR = ROOT / "static" / "fonts"
CSS_PATH = ROOT / "static" / "css" / "fonts.css"

#: Inter 700 is deliberately absent. The design uses 400 and 600 only, and
#: `b, strong` is styled to 600 -- without that, an unstyled `<b>` pulls a whole
#: extra 48 kB face that nothing in the stylesheet ever asks for.
#: Roboto Mono 500 is kept: it is declared but only fetched if something selects
#: it, so it costs repository size and no transfer.
FAMILIES = "family=Anton&family=Inter:wght@400;600&family=Roboto+Mono:wght@400;500"
CSS_URL = f"https://fonts.googleapis.com/css2?{FAMILIES}&display=swap"

# Google serves a different stylesheet per user agent. This one asks for the
# modern woff2 subset; without it you get a truetype fallback three times the
# size, which defeats the point of doing this at all.
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36")


def fetch(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(request, timeout=30) as response:
        return response.read()


def main() -> int:
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    css = fetch(CSS_URL).decode("utf-8")

    # Google emits one @font-face per unicode subset (latin, latin-ext, cyrillic,
    # greek, vietnamese). Keeping only latin and latin-ext drops about two thirds
    # of the bytes; a team name in Greek would fall back to the system stack,
    # which is a trade worth making for a ten-person league in one bar.
    blocks = re.findall(r"/\*\s*([\w\-\[\]]+)\s*\*/\s*(@font-face\s*\{.*?\})", css, re.S)
    kept: list[str] = []
    downloaded = 0
    total = 0

    for subset, block in blocks:
        if subset not in ("latin", "latin-ext"):
            continue
        match = re.search(r"url\((https://fonts\.gstatic\.com/[^)]+\.woff2)\)", block)
        if not match:
            continue
        url = match.group(1)
        family = re.search(r"font-family:\s*'([^']+)'", block).group(1).replace(" ", "-").lower()
        weight = (re.search(r"font-weight:\s*(\d+)", block) or [None, "400"])[1]
        name = f"{family}-{weight}-{subset}.woff2"

        target = FONT_DIR / name
        if not target.is_file():
            data = fetch(url)
            target.write_bytes(data)
            downloaded += 1
        total += target.stat().st_size
        kept.append(block.replace(url, f"/static/fonts/{name}"))

    header = (
        "/* Self-hosted webfonts. Generated by tools/fetch_fonts.py -- do not edit.\n"
        " *\n"
        " * Latin and latin-ext subsets only: the other four Google ships are two\n"
        " * thirds of the bytes and no team in this league is going to be named in\n"
        " * Greek. Served from our own origin because the target environment is a\n"
        " * bar's shared wifi, where a third-party font host is a DNS lookup, a TLS\n"
        " * handshake and a round trip before a single glyph is drawn.\n"
        " *\n"
        " * Anton, Inter and Roboto Mono are all SIL Open Font Licence 1.1.\n"
        " * See static/js/LICENCES.md.\n"
        " */\n\n"
    )
    CSS_PATH.write_text(header + "\n\n".join(kept) + "\n", encoding="utf-8")

    print(f"{len(kept)} faces, {downloaded} newly downloaded, {total / 1000:.0f} kB total")
    print(f"  {CSS_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
