#!/usr/bin/env python3
"""Generate static/audio/LICENCES.md from data/audio_sources.json.

    python3 tools/make_licences.py
    python3 tools/make_licences.py --check    # fail if the file is out of date

The original rule here was that every sound is synthesised, so nothing has a
licence to track and the credits file cannot drift. That rule bought real
safety and cost the audio: the horns carried under 8% of their energy above
2 kHz, which is what "dull, like a tone through a blanket" measures as.

Sampled sound is allowed now, and the safety is kept a different way: the
credits are derived from the manifest rather than written beside it, and
`--check` fails the build if the two disagree. A sound cannot enter the sprite
without a licence line, because the same file is what the builder reads.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "data" / "audio_sources.json"
OUT = ROOT / "static" / "audio" / "LICENCES.md"

ROLES = {
    "bed_epic": "The Sunday-night theme, under the Big Board",
    "bed_party": "The watch-party loop, under a phone",
    "horn_01": "An ordinary touchdown", "horn_02": "A better one, and lead changes",
    "horn_03": "Long touchdowns, clinches, hundred-point milestones",
    "trombone": "Bench disasters and goose eggs. The sad one",
    "whoosh": "Big plays", "riser": "The red-zone countdown",
    "chime": "Clinches and good news", "doom": "Mathematically finished",
    "scratch": "A record stopping: the joke's rimshot",
    "buzzer": "A goose egg from a starter", "crowd": "Under the big moments",
    "tap": "A finger on a control", "flip": "A card turning over",
    "rip": "The pack tearing open",
}


def render(spec: dict) -> str:
    sounds = spec.get("sounds", {})
    downloads = spec.get("downloads", {})

    lines = [
        "# Audio assets",
        "",
        "**Generated by `tools/make_licences.py` from `data/audio_sources.json`. Do not edit.**",
        "",
        "Every asset in this directory needs a line here, and gets one by construction:",
        "the builder and this file read the same manifest, so a sound cannot reach the",
        "sprite without a licence line. `tools/make_licences.py --check` fails the build",
        "if they disagree.",
        "",
        "| File | Source | Licence |",
        "|---|---|---|",
        "| `sprite.mp3`, `sprite.ogg` | Built by `tools/make_audio.py` from the sounds below | Mixed; see the table |",
        "| `sprite.json` | Generated alongside them | Ours outright, MIT |",
        "| `bed-epic.mp3`, `bed-epic.ogg` | The Big Board's theme; see the table below | See below |",
        "| `bed-party.mp3`, `bed-party.ogg` | The phone's watch-party loop; see below | See below |",
        "| `bed.mp3`, `bed.ogg` | The synthesised pad, kept as the fallback | Ours outright, MIT |",
        "",
        "## The sounds",
        "",
        "| Sound | Used for | Source | Licence |",
        "|---|---|---|---|",
    ]
    for name in sorted(ROLES):
        role = ROLES[name]
        if name in sounds:
            origin = downloads[sounds[name]["from"]]
            source = f"[{origin['source']}]({origin['page']}) by {origin['author']}"
            licence = f"[{origin['licence']}]({origin['licence_url']})"
        else:
            source = "Synthesised by `tools/make_audio.py`"
            licence = "Ours outright, MIT"
        lines.append(f"| `{name}` | {role} | {source} | {licence} |")

    attributed = sorted(
        (k, e) for k, e in downloads.items() if e["licence"] != "CC0 1.0"
    )
    if attributed:
        lines += [
            "",
            "## Attribution",
            "",
            "**These credits are required.** They are part of the licence on the music",
            "below, and this file is what discharges that obligation for anyone who",
            "clones the repository. It is generated, so it cannot fall out of step with",
            "what is actually in the sprite.",
            "",
        ]
        for _key, entry in attributed:
            lines.append(
                f"- *[{entry['source']}]({entry['page']})* by **{entry['author']}**, "
                f"licensed [{entry['licence']}]({entry['licence_url']})."
            )

    lines += [
        "",
        "## Why CC0 for effects, and CC-BY only for music",
        "",
        "Two rules, because one could not produce the app.",
        "",
        "Sound effects are **CC0 only**. This repository is public and MIT, so an asset",
        "with an attribution requirement puts an obligation on everyone who clones it,",
        "one they will not know they have, and a non-commercial clause would make the",
        "repository undistributable.",
        "",
        "Music may be **CC-BY**. The sports-broadcast idiom does not exist under CC0: it",
        "gives you epic percussion, taiko and marching snare, but no melodic brass-rock",
        "theme, and a CC0 search for \"rock anthem\" returns nothing at all. Attribution",
        "is acceptable there precisely because this file is generated from the manifest",
        "the builder reads, and `tools/make_licences.py --check` fails the build when the",
        "two disagree: the obligation travels with the repository by construction rather",
        "than by anyone remembering. `tests/test_audio_sources.py` enforces both rules,",
        "including that no *effect* may be CC-BY.",
        "",
        "None of this covers the things that are actually off limits, which are not a",
        "licensing question at all: the Sunday Night Football theme and \"Gonna Fly Now\"",
        "are copyrighted compositions owned by NBC and by Bill Conti's publisher, as are",
        "team fight songs and stadium anthem recordings. The **idiom** is a genre",
        "convention and is fair game. The tunes are not. No archive used here contains",
        "them and none may be ripped in.",
        "",
        "## Provenance",
        "",
        "| Download | sha256 | Bytes |",
        "|---|---|---|",
    ]
    for key, entry in sorted(downloads.items()):
        lines.append(f"| [{entry['source']}]({entry['url']}) | `{entry['sha256'][:16]}…` | {entry['bytes']:,} |")
    lines += [
        "",
        "The checksum is checked on every fetch, so a silently re-cut upstream file fails",
        "the build rather than changing what the bar hears.",
        "",
        "## Rebuilding",
        "",
        "```bash",
        "python3 tools/fetch_audio.py     # download, verify, measure",
        "python3 tools/make_audio.py      # build the sprite and the bed",
        "python3 tools/make_licences.py   # regenerate this file",
        "```",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="fail if out of date, write nothing")
    args = parser.parse_args()

    wanted = render(json.loads(MANIFEST.read_text("utf-8")))
    if args.check:
        current = OUT.read_text("utf-8") if OUT.is_file() else ""
        if current != wanted:
            print("LICENCES.md is out of date. Run tools/make_licences.py.", file=sys.stderr)
            return 1
        print("LICENCES.md matches the manifest.")
        return 0

    OUT.write_text(wanted, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
